name: build-android

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build android
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      - name: test project
        run: flutter test
      - run: flutter build ios --release --no-codesign
      - run: flutter build apk