name: build-android

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Build Project
        run: flutter build apk
